package model

import (
	"fmt"
	"sort"
	"strings"
)

type DocumentClassification struct {
	Code           string
	Label          string
	Phase          string
	RetentionYears int
	Confidential   bool
	Editable       bool
	SortOrder      int
}

var documentClassifications = []DocumentClassification{
	{
		Code:           "intake-client-instruction",
		Label:          "client instruction",
		Phase:          "intake",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      1,
	},
	{
		Code:           "intake-engagement-letter",
		Label:          "engagement letter",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      2,
	},
	{
		Code:           "intake-conflict-check",
		Label:          "conflict check",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      3,
	},
	{
		Code:           "intake-identity-record",
		Label:          "identity record",
		Phase:          "intake",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      4,
	},
	{
		Code:           "intake-authority-letter",
		Label:          "authority letter",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      5,
	},
	{
		Code:           "intake-fact-memo",
		Label:          "fact memo",
		Phase:          "intake",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      6,
	},
	{
		Code:           "intake-chronology",
		Label:          "chronology",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      7,
	},
	{
		Code:           "intake-witness-note",
		Label:          "witness note",
		Phase:          "intake",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      8,
	},
	{
		Code:           "intake-expert-opinion",
		Label:          "expert opinion",
		Phase:          "intake",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      9,
	},
	{
		Code:           "intake-evidence-index",
		Label:          "evidence index",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      10,
	},
	{
		Code:           "intake-contract-original",
		Label:          "contract original",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      11,
	},
	{
		Code:           "intake-contract-translation",
		Label:          "contract translation",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      12,
	},
	{
		Code:           "intake-correspondence",
		Label:          "correspondence",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      13,
	},
	{
		Code:           "intake-demand-letter",
		Label:          "demand letter",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      14,
	},
	{
		Code:           "intake-settlement-draft",
		Label:          "settlement draft",
		Phase:          "intake",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      15,
	},
	{
		Code:           "intake-settlement-final",
		Label:          "settlement final",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      16,
	},
	{
		Code:           "intake-pleading-draft",
		Label:          "pleading draft",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      17,
	},
	{
		Code:           "intake-pleading-filed",
		Label:          "pleading filed",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      18,
	},
	{
		Code:           "intake-service-proof",
		Label:          "service proof",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      19,
	},
	{
		Code:           "intake-court-notice",
		Label:          "court notice",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      20,
	},
	{
		Code:           "intake-motion",
		Label:          "motion",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      21,
	},
	{
		Code:           "intake-response",
		Label:          "response",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      22,
	},
	{
		Code:           "intake-disclosure-list",
		Label:          "disclosure list",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      23,
	},
	{
		Code:           "intake-hearing-note",
		Label:          "hearing note",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      24,
	},
	{
		Code:           "intake-judgment",
		Label:          "judgment",
		Phase:          "intake",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      25,
	},
	{
		Code:           "intake-appeal-note",
		Label:          "appeal note",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      26,
	},
	{
		Code:           "intake-enforcement-request",
		Label:          "enforcement request",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      27,
	},
	{
		Code:           "intake-payment-record",
		Label:          "payment record",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      28,
	},
	{
		Code:           "intake-closing-report",
		Label:          "closing report",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      29,
	},
	{
		Code:           "intake-retention-notice",
		Label:          "retention notice",
		Phase:          "intake",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      30,
	},
	{
		Code:           "investigation-client-instruction",
		Label:          "client instruction",
		Phase:          "investigation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      31,
	},
	{
		Code:           "investigation-engagement-letter",
		Label:          "engagement letter",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      32,
	},
	{
		Code:           "investigation-conflict-check",
		Label:          "conflict check",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      33,
	},
	{
		Code:           "investigation-identity-record",
		Label:          "identity record",
		Phase:          "investigation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      34,
	},
	{
		Code:           "investigation-authority-letter",
		Label:          "authority letter",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      35,
	},
	{
		Code:           "investigation-fact-memo",
		Label:          "fact memo",
		Phase:          "investigation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      36,
	},
	{
		Code:           "investigation-chronology",
		Label:          "chronology",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      37,
	},
	{
		Code:           "investigation-witness-note",
		Label:          "witness note",
		Phase:          "investigation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      38,
	},
	{
		Code:           "investigation-expert-opinion",
		Label:          "expert opinion",
		Phase:          "investigation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      39,
	},
	{
		Code:           "investigation-evidence-index",
		Label:          "evidence index",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      40,
	},
	{
		Code:           "investigation-contract-original",
		Label:          "contract original",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      41,
	},
	{
		Code:           "investigation-contract-translation",
		Label:          "contract translation",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      42,
	},
	{
		Code:           "investigation-correspondence",
		Label:          "correspondence",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      43,
	},
	{
		Code:           "investigation-demand-letter",
		Label:          "demand letter",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      44,
	},
	{
		Code:           "investigation-settlement-draft",
		Label:          "settlement draft",
		Phase:          "investigation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      45,
	},
	{
		Code:           "investigation-settlement-final",
		Label:          "settlement final",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      46,
	},
	{
		Code:           "investigation-pleading-draft",
		Label:          "pleading draft",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      47,
	},
	{
		Code:           "investigation-pleading-filed",
		Label:          "pleading filed",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      48,
	},
	{
		Code:           "investigation-service-proof",
		Label:          "service proof",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      49,
	},
	{
		Code:           "investigation-court-notice",
		Label:          "court notice",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      50,
	},
	{
		Code:           "investigation-motion",
		Label:          "motion",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      51,
	},
	{
		Code:           "investigation-response",
		Label:          "response",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      52,
	},
	{
		Code:           "investigation-disclosure-list",
		Label:          "disclosure list",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      53,
	},
	{
		Code:           "investigation-hearing-note",
		Label:          "hearing note",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      54,
	},
	{
		Code:           "investigation-judgment",
		Label:          "judgment",
		Phase:          "investigation",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      55,
	},
	{
		Code:           "investigation-appeal-note",
		Label:          "appeal note",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      56,
	},
	{
		Code:           "investigation-enforcement-request",
		Label:          "enforcement request",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      57,
	},
	{
		Code:           "investigation-payment-record",
		Label:          "payment record",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      58,
	},
	{
		Code:           "investigation-closing-report",
		Label:          "closing report",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      59,
	},
	{
		Code:           "investigation-retention-notice",
		Label:          "retention notice",
		Phase:          "investigation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      60,
	},
	{
		Code:           "negotiation-client-instruction",
		Label:          "client instruction",
		Phase:          "negotiation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      61,
	},
	{
		Code:           "negotiation-engagement-letter",
		Label:          "engagement letter",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      62,
	},
	{
		Code:           "negotiation-conflict-check",
		Label:          "conflict check",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      63,
	},
	{
		Code:           "negotiation-identity-record",
		Label:          "identity record",
		Phase:          "negotiation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      64,
	},
	{
		Code:           "negotiation-authority-letter",
		Label:          "authority letter",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      65,
	},
	{
		Code:           "negotiation-fact-memo",
		Label:          "fact memo",
		Phase:          "negotiation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      66,
	},
	{
		Code:           "negotiation-chronology",
		Label:          "chronology",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      67,
	},
	{
		Code:           "negotiation-witness-note",
		Label:          "witness note",
		Phase:          "negotiation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      68,
	},
	{
		Code:           "negotiation-expert-opinion",
		Label:          "expert opinion",
		Phase:          "negotiation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      69,
	},
	{
		Code:           "negotiation-evidence-index",
		Label:          "evidence index",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      70,
	},
	{
		Code:           "negotiation-contract-original",
		Label:          "contract original",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      71,
	},
	{
		Code:           "negotiation-contract-translation",
		Label:          "contract translation",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      72,
	},
	{
		Code:           "negotiation-correspondence",
		Label:          "correspondence",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      73,
	},
	{
		Code:           "negotiation-demand-letter",
		Label:          "demand letter",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      74,
	},
	{
		Code:           "negotiation-settlement-draft",
		Label:          "settlement draft",
		Phase:          "negotiation",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      75,
	},
	{
		Code:           "negotiation-settlement-final",
		Label:          "settlement final",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      76,
	},
	{
		Code:           "negotiation-pleading-draft",
		Label:          "pleading draft",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      77,
	},
	{
		Code:           "negotiation-pleading-filed",
		Label:          "pleading filed",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      78,
	},
	{
		Code:           "negotiation-service-proof",
		Label:          "service proof",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      79,
	},
	{
		Code:           "negotiation-court-notice",
		Label:          "court notice",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      80,
	},
	{
		Code:           "negotiation-motion",
		Label:          "motion",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      81,
	},
	{
		Code:           "negotiation-response",
		Label:          "response",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      82,
	},
	{
		Code:           "negotiation-disclosure-list",
		Label:          "disclosure list",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      83,
	},
	{
		Code:           "negotiation-hearing-note",
		Label:          "hearing note",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      84,
	},
	{
		Code:           "negotiation-judgment",
		Label:          "judgment",
		Phase:          "negotiation",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      85,
	},
	{
		Code:           "negotiation-appeal-note",
		Label:          "appeal note",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      86,
	},
	{
		Code:           "negotiation-enforcement-request",
		Label:          "enforcement request",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      87,
	},
	{
		Code:           "negotiation-payment-record",
		Label:          "payment record",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      88,
	},
	{
		Code:           "negotiation-closing-report",
		Label:          "closing report",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      89,
	},
	{
		Code:           "negotiation-retention-notice",
		Label:          "retention notice",
		Phase:          "negotiation",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      90,
	},
	{
		Code:           "filing-client-instruction",
		Label:          "client instruction",
		Phase:          "filing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      91,
	},
	{
		Code:           "filing-engagement-letter",
		Label:          "engagement letter",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      92,
	},
	{
		Code:           "filing-conflict-check",
		Label:          "conflict check",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      93,
	},
	{
		Code:           "filing-identity-record",
		Label:          "identity record",
		Phase:          "filing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      94,
	},
	{
		Code:           "filing-authority-letter",
		Label:          "authority letter",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      95,
	},
	{
		Code:           "filing-fact-memo",
		Label:          "fact memo",
		Phase:          "filing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      96,
	},
	{
		Code:           "filing-chronology",
		Label:          "chronology",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      97,
	},
	{
		Code:           "filing-witness-note",
		Label:          "witness note",
		Phase:          "filing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      98,
	},
	{
		Code:           "filing-expert-opinion",
		Label:          "expert opinion",
		Phase:          "filing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      99,
	},
	{
		Code:           "filing-evidence-index",
		Label:          "evidence index",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      100,
	},
	{
		Code:           "filing-contract-original",
		Label:          "contract original",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      101,
	},
	{
		Code:           "filing-contract-translation",
		Label:          "contract translation",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      102,
	},
	{
		Code:           "filing-correspondence",
		Label:          "correspondence",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      103,
	},
	{
		Code:           "filing-demand-letter",
		Label:          "demand letter",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      104,
	},
	{
		Code:           "filing-settlement-draft",
		Label:          "settlement draft",
		Phase:          "filing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      105,
	},
	{
		Code:           "filing-settlement-final",
		Label:          "settlement final",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      106,
	},
	{
		Code:           "filing-pleading-draft",
		Label:          "pleading draft",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      107,
	},
	{
		Code:           "filing-pleading-filed",
		Label:          "pleading filed",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      108,
	},
	{
		Code:           "filing-service-proof",
		Label:          "service proof",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      109,
	},
	{
		Code:           "filing-court-notice",
		Label:          "court notice",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      110,
	},
	{
		Code:           "filing-motion",
		Label:          "motion",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      111,
	},
	{
		Code:           "filing-response",
		Label:          "response",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      112,
	},
	{
		Code:           "filing-disclosure-list",
		Label:          "disclosure list",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      113,
	},
	{
		Code:           "filing-hearing-note",
		Label:          "hearing note",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      114,
	},
	{
		Code:           "filing-judgment",
		Label:          "judgment",
		Phase:          "filing",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      115,
	},
	{
		Code:           "filing-appeal-note",
		Label:          "appeal note",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      116,
	},
	{
		Code:           "filing-enforcement-request",
		Label:          "enforcement request",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      117,
	},
	{
		Code:           "filing-payment-record",
		Label:          "payment record",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      118,
	},
	{
		Code:           "filing-closing-report",
		Label:          "closing report",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      119,
	},
	{
		Code:           "filing-retention-notice",
		Label:          "retention notice",
		Phase:          "filing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      120,
	},
	{
		Code:           "discovery-client-instruction",
		Label:          "client instruction",
		Phase:          "discovery",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      121,
	},
	{
		Code:           "discovery-engagement-letter",
		Label:          "engagement letter",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      122,
	},
	{
		Code:           "discovery-conflict-check",
		Label:          "conflict check",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      123,
	},
	{
		Code:           "discovery-identity-record",
		Label:          "identity record",
		Phase:          "discovery",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      124,
	},
	{
		Code:           "discovery-authority-letter",
		Label:          "authority letter",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      125,
	},
	{
		Code:           "discovery-fact-memo",
		Label:          "fact memo",
		Phase:          "discovery",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      126,
	},
	{
		Code:           "discovery-chronology",
		Label:          "chronology",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      127,
	},
	{
		Code:           "discovery-witness-note",
		Label:          "witness note",
		Phase:          "discovery",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      128,
	},
	{
		Code:           "discovery-expert-opinion",
		Label:          "expert opinion",
		Phase:          "discovery",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      129,
	},
	{
		Code:           "discovery-evidence-index",
		Label:          "evidence index",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      130,
	},
	{
		Code:           "discovery-contract-original",
		Label:          "contract original",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      131,
	},
	{
		Code:           "discovery-contract-translation",
		Label:          "contract translation",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      132,
	},
	{
		Code:           "discovery-correspondence",
		Label:          "correspondence",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      133,
	},
	{
		Code:           "discovery-demand-letter",
		Label:          "demand letter",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      134,
	},
	{
		Code:           "discovery-settlement-draft",
		Label:          "settlement draft",
		Phase:          "discovery",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      135,
	},
	{
		Code:           "discovery-settlement-final",
		Label:          "settlement final",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      136,
	},
	{
		Code:           "discovery-pleading-draft",
		Label:          "pleading draft",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      137,
	},
	{
		Code:           "discovery-pleading-filed",
		Label:          "pleading filed",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      138,
	},
	{
		Code:           "discovery-service-proof",
		Label:          "service proof",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      139,
	},
	{
		Code:           "discovery-court-notice",
		Label:          "court notice",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      140,
	},
	{
		Code:           "discovery-motion",
		Label:          "motion",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      141,
	},
	{
		Code:           "discovery-response",
		Label:          "response",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      142,
	},
	{
		Code:           "discovery-disclosure-list",
		Label:          "disclosure list",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      143,
	},
	{
		Code:           "discovery-hearing-note",
		Label:          "hearing note",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      144,
	},
	{
		Code:           "discovery-judgment",
		Label:          "judgment",
		Phase:          "discovery",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      145,
	},
	{
		Code:           "discovery-appeal-note",
		Label:          "appeal note",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      146,
	},
	{
		Code:           "discovery-enforcement-request",
		Label:          "enforcement request",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      147,
	},
	{
		Code:           "discovery-payment-record",
		Label:          "payment record",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      148,
	},
	{
		Code:           "discovery-closing-report",
		Label:          "closing report",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      149,
	},
	{
		Code:           "discovery-retention-notice",
		Label:          "retention notice",
		Phase:          "discovery",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      150,
	},
	{
		Code:           "hearing-client-instruction",
		Label:          "client instruction",
		Phase:          "hearing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      151,
	},
	{
		Code:           "hearing-engagement-letter",
		Label:          "engagement letter",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      152,
	},
	{
		Code:           "hearing-conflict-check",
		Label:          "conflict check",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      153,
	},
	{
		Code:           "hearing-identity-record",
		Label:          "identity record",
		Phase:          "hearing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      154,
	},
	{
		Code:           "hearing-authority-letter",
		Label:          "authority letter",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      155,
	},
	{
		Code:           "hearing-fact-memo",
		Label:          "fact memo",
		Phase:          "hearing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      156,
	},
	{
		Code:           "hearing-chronology",
		Label:          "chronology",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      157,
	},
	{
		Code:           "hearing-witness-note",
		Label:          "witness note",
		Phase:          "hearing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      158,
	},
	{
		Code:           "hearing-expert-opinion",
		Label:          "expert opinion",
		Phase:          "hearing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      159,
	},
	{
		Code:           "hearing-evidence-index",
		Label:          "evidence index",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      160,
	},
	{
		Code:           "hearing-contract-original",
		Label:          "contract original",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      161,
	},
	{
		Code:           "hearing-contract-translation",
		Label:          "contract translation",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      162,
	},
	{
		Code:           "hearing-correspondence",
		Label:          "correspondence",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      163,
	},
	{
		Code:           "hearing-demand-letter",
		Label:          "demand letter",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      164,
	},
	{
		Code:           "hearing-settlement-draft",
		Label:          "settlement draft",
		Phase:          "hearing",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      165,
	},
	{
		Code:           "hearing-settlement-final",
		Label:          "settlement final",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      166,
	},
	{
		Code:           "hearing-pleading-draft",
		Label:          "pleading draft",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      167,
	},
	{
		Code:           "hearing-pleading-filed",
		Label:          "pleading filed",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      168,
	},
	{
		Code:           "hearing-service-proof",
		Label:          "service proof",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      169,
	},
	{
		Code:           "hearing-court-notice",
		Label:          "court notice",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      170,
	},
	{
		Code:           "hearing-motion",
		Label:          "motion",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      171,
	},
	{
		Code:           "hearing-response",
		Label:          "response",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      172,
	},
	{
		Code:           "hearing-disclosure-list",
		Label:          "disclosure list",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      173,
	},
	{
		Code:           "hearing-hearing-note",
		Label:          "hearing note",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      174,
	},
	{
		Code:           "hearing-judgment",
		Label:          "judgment",
		Phase:          "hearing",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      175,
	},
	{
		Code:           "hearing-appeal-note",
		Label:          "appeal note",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      176,
	},
	{
		Code:           "hearing-enforcement-request",
		Label:          "enforcement request",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      177,
	},
	{
		Code:           "hearing-payment-record",
		Label:          "payment record",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      178,
	},
	{
		Code:           "hearing-closing-report",
		Label:          "closing report",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      179,
	},
	{
		Code:           "hearing-retention-notice",
		Label:          "retention notice",
		Phase:          "hearing",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      180,
	},
	{
		Code:           "appeal-client-instruction",
		Label:          "client instruction",
		Phase:          "appeal",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      181,
	},
	{
		Code:           "appeal-engagement-letter",
		Label:          "engagement letter",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      182,
	},
	{
		Code:           "appeal-conflict-check",
		Label:          "conflict check",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      183,
	},
	{
		Code:           "appeal-identity-record",
		Label:          "identity record",
		Phase:          "appeal",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      184,
	},
	{
		Code:           "appeal-authority-letter",
		Label:          "authority letter",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      185,
	},
	{
		Code:           "appeal-fact-memo",
		Label:          "fact memo",
		Phase:          "appeal",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      186,
	},
	{
		Code:           "appeal-chronology",
		Label:          "chronology",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      187,
	},
	{
		Code:           "appeal-witness-note",
		Label:          "witness note",
		Phase:          "appeal",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      188,
	},
	{
		Code:           "appeal-expert-opinion",
		Label:          "expert opinion",
		Phase:          "appeal",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      189,
	},
	{
		Code:           "appeal-evidence-index",
		Label:          "evidence index",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      190,
	},
	{
		Code:           "appeal-contract-original",
		Label:          "contract original",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      191,
	},
	{
		Code:           "appeal-contract-translation",
		Label:          "contract translation",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      192,
	},
	{
		Code:           "appeal-correspondence",
		Label:          "correspondence",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      193,
	},
	{
		Code:           "appeal-demand-letter",
		Label:          "demand letter",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      194,
	},
	{
		Code:           "appeal-settlement-draft",
		Label:          "settlement draft",
		Phase:          "appeal",
		RetentionYears: 10,
		Confidential:   true,
		Editable:       true,
		SortOrder:      195,
	},
	{
		Code:           "appeal-settlement-final",
		Label:          "settlement final",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      196,
	},
	{
		Code:           "appeal-pleading-draft",
		Label:          "pleading draft",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      197,
	},
	{
		Code:           "appeal-pleading-filed",
		Label:          "pleading filed",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      198,
	},
	{
		Code:           "appeal-service-proof",
		Label:          "service proof",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      199,
	},
	{
		Code:           "appeal-court-notice",
		Label:          "court notice",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      200,
	},
	{
		Code:           "appeal-motion",
		Label:          "motion",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      201,
	},
	{
		Code:           "appeal-response",
		Label:          "response",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      202,
	},
	{
		Code:           "appeal-disclosure-list",
		Label:          "disclosure list",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      203,
	},
	{
		Code:           "appeal-hearing-note",
		Label:          "hearing note",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      204,
	},
	{
		Code:           "appeal-judgment",
		Label:          "judgment",
		Phase:          "appeal",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      205,
	},
	{
		Code:           "appeal-appeal-note",
		Label:          "appeal note",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      206,
	},
	{
		Code:           "appeal-enforcement-request",
		Label:          "enforcement request",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      207,
	},
	{
		Code:           "appeal-payment-record",
		Label:          "payment record",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       false,
		SortOrder:      208,
	},
	{
		Code:           "appeal-closing-report",
		Label:          "closing report",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      209,
	},
	{
		Code:           "appeal-retention-notice",
		Label:          "retention notice",
		Phase:          "appeal",
		RetentionYears: 7,
		Confidential:   false,
		Editable:       true,
		SortOrder:      210,
	},
	{
		Code:           "enforcement-client-instruction",
		Label:          "client instruction",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   true,
		Editable:       true,
		SortOrder:      211,
	},
	{
		Code:           "enforcement-engagement-letter",
		Label:          "engagement letter",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      212,
	},
	{
		Code:           "enforcement-conflict-check",
		Label:          "conflict check",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      213,
	},
	{
		Code:           "enforcement-identity-record",
		Label:          "identity record",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   true,
		Editable:       true,
		SortOrder:      214,
	},
	{
		Code:           "enforcement-authority-letter",
		Label:          "authority letter",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      215,
	},
	{
		Code:           "enforcement-fact-memo",
		Label:          "fact memo",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   true,
		Editable:       true,
		SortOrder:      216,
	},
	{
		Code:           "enforcement-chronology",
		Label:          "chronology",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      217,
	},
	{
		Code:           "enforcement-witness-note",
		Label:          "witness note",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   true,
		Editable:       true,
		SortOrder:      218,
	},
	{
		Code:           "enforcement-expert-opinion",
		Label:          "expert opinion",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   true,
		Editable:       true,
		SortOrder:      219,
	},
	{
		Code:           "enforcement-evidence-index",
		Label:          "evidence index",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      220,
	},
	{
		Code:           "enforcement-contract-original",
		Label:          "contract original",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      221,
	},
	{
		Code:           "enforcement-contract-translation",
		Label:          "contract translation",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      222,
	},
	{
		Code:           "enforcement-correspondence",
		Label:          "correspondence",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      223,
	},
	{
		Code:           "enforcement-demand-letter",
		Label:          "demand letter",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      224,
	},
	{
		Code:           "enforcement-settlement-draft",
		Label:          "settlement draft",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   true,
		Editable:       true,
		SortOrder:      225,
	},
	{
		Code:           "enforcement-settlement-final",
		Label:          "settlement final",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      226,
	},
	{
		Code:           "enforcement-pleading-draft",
		Label:          "pleading draft",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      227,
	},
	{
		Code:           "enforcement-pleading-filed",
		Label:          "pleading filed",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      228,
	},
	{
		Code:           "enforcement-service-proof",
		Label:          "service proof",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      229,
	},
	{
		Code:           "enforcement-court-notice",
		Label:          "court notice",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      230,
	},
	{
		Code:           "enforcement-motion",
		Label:          "motion",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      231,
	},
	{
		Code:           "enforcement-response",
		Label:          "response",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      232,
	},
	{
		Code:           "enforcement-disclosure-list",
		Label:          "disclosure list",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      233,
	},
	{
		Code:           "enforcement-hearing-note",
		Label:          "hearing note",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      234,
	},
	{
		Code:           "enforcement-judgment",
		Label:          "judgment",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      235,
	},
	{
		Code:           "enforcement-appeal-note",
		Label:          "appeal note",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      236,
	},
	{
		Code:           "enforcement-enforcement-request",
		Label:          "enforcement request",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      237,
	},
	{
		Code:           "enforcement-payment-record",
		Label:          "payment record",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       false,
		SortOrder:      238,
	},
	{
		Code:           "enforcement-closing-report",
		Label:          "closing report",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      239,
	},
	{
		Code:           "enforcement-retention-notice",
		Label:          "retention notice",
		Phase:          "enforcement",
		RetentionYears: 15,
		Confidential:   false,
		Editable:       true,
		SortOrder:      240,
	},
}

func DocumentClassifications() []DocumentClassification {
	result := make([]DocumentClassification, len(documentClassifications))
	copy(result, documentClassifications)
	return result
}

func Classification(code string) (DocumentClassification, error) {
	for _, classification := range documentClassifications {
		if classification.Code == code {
			return classification, nil
		}
	}
	return DocumentClassification{}, fmt.Errorf("classification %s is unknown", code)
}

func ClassificationsByPhase(phase string) []DocumentClassification {
	result := []DocumentClassification{}
	for _, classification := range documentClassifications {
		if classification.Phase == phase {
			result = append(result, classification)
		}
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].SortOrder < result[j].SortOrder
	})
	return result
}

func SearchClassifications(query string, includeConfidential bool) []DocumentClassification {
	normalized := strings.ToLower(strings.TrimSpace(query))
	result := []DocumentClassification{}
	for _, classification := range documentClassifications {
		if classification.Confidential && !includeConfidential {
			continue
		}
		if normalized != "" && !strings.Contains(classification.Code, normalized) && !strings.Contains(classification.Label, normalized) {
			continue
		}
		result = append(result, classification)
	}
	return result
}

func RetentionDeadline(createdAt int64, code string) (int64, error) {
	classification, err := Classification(code)
	if err != nil {
		return 0, err
	}
	const secondsPerYear int64 = 365 * 24 * 60 * 60
	return createdAt + int64(classification.RetentionYears)*secondsPerYear, nil
}
